--- #YAML:1.0
name:                Proc-Exists
version:             0.92_01
abstract:            quickly check for process existence
license:             perl
generated_by:        makemaker at first, then by hand
distribution_type:   module
requires:     
build_requires:     
    ExtUtils::MakeMaker:           0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Brian Szymanski <ski-cpan@allafrica.com>
