--- #YAML:1.0
name:                Proc-Exists
version:             0.09
abstract:            quickly check for process existence
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Brian Szymanski <ski-cpan@allafrica.com>
